import { existsSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../..");

/** Temp file to communicate ownership state to global-teardown */
const STATE_FILE = join(tmpdir(), "playwright-supabase-state.json");

async function globalSetup() {
  const { isCI, isSupabaseInstalled, isSupabaseRunning, startSupabase, getSupabaseCredentials } =
    await import("../../scripts/supabase-lifecycle.mjs");

  if (isCI()) {
    console.log("[global-setup] CI detected — using remote Supabase");
    return;
  }

  if (!isSupabaseInstalled()) {
    throw new Error(
      "Supabase CLI not found.\n" +
        "Install: brew install supabase/tap/supabase\n" +
        "Or run tests against remote Supabase by setting CI=true with env vars."
    );
  }

  const wasAlreadyRunning = isSupabaseRunning();
  startSupabase(); // idempotent — skips if already running

  // Store ownership state for teardown
  writeFileSync(STATE_FILE, JSON.stringify({ startedByPlaywright: !wasAlreadyRunning }), "utf-8");

  // Auto-create .env.test if missing
  const envTestPath = resolve(ROOT, ".env.test");
  if (!existsSync(envTestPath)) {
    console.log("[global-setup] Creating .env.test from local Supabase...");
    const creds = getSupabaseCredentials();
    const content = [
      "# Auto-generated by Playwright global-setup (local Supabase dev keys)",
      "# This file is gitignored — do not commit",
      `SUPABASE_URL=${creds.apiUrl}`,
      `SUPABASE_SERVICE_ROLE_KEY=${creds.serviceRoleKey}`,
      "",
    ].join("\n");
    writeFileSync(envTestPath, content, "utf-8");
    console.log("[global-setup] .env.test created");
  }
}

export default globalSetup;
