-- Migration: Add Push Subscriptions
-- Purpose: Create push_subscriptions table and budget threshold check function for PWA push notifications (Phase C)
-- References:
--   - DATABASE.md lines 9-42: Push subscriptions schema
--   - DATABASE.md lines 441-501: Transfer exclusion patterns
--   - docs/implementation/chunks/043-push-notifications/instructions.md
--   - Web Push API: https://developer.mozilla.org/en-US/docs/Web/API/Push_API
-- Safety: This migration is ADDITIVE ONLY - no data loss risk
-- Note: No snapshot required (new table and function creation)

BEGIN;

-- ============================================================================
-- Prerequisites Check
-- ============================================================================
-- Verify required dependencies before creating push notification schema

DO $$
BEGIN
  -- Check 1: Verify devices table exists (from chunk 027)
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
    AND table_name = 'devices'
  ) THEN
    RAISE EXCEPTION 'devices table does not exist. Please apply chunk 027 migration first (20251028025558_add_devices_table.sql)';
  END IF;

  -- Check 2: Verify profiles.notification_preferences column exists
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'profiles'
    AND column_name = 'notification_preferences'
  ) THEN
    RAISE EXCEPTION 'profiles.notification_preferences column does not exist. Ensure profiles migration (20251023224800_create_profiles.sql) has notification_preferences JSONB column.';
  END IF;

  RAISE NOTICE '✓ Prerequisites verified: devices table and profiles.notification_preferences exist';
END $$;

-- ============================================================================
-- Trigger Function (Defensive - may already exist from other tables)
-- ============================================================================

-- Ensure trigger function exists for updated_at auto-update
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Push Subscriptions Table
-- ============================================================================

CREATE TABLE push_subscriptions (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Ownership
  -- Links subscription to authenticated user
  -- Using auth.users(id) directly (matches profiles/devices table pattern)
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Device association
  -- CRITICAL: Push subscriptions are device-scoped (each browser/PWA instance has unique endpoint)
  -- Links to devices table for multi-device push support
  -- Cascade delete ensures cleanup when device is removed
  device_id TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,

  -- Web Push subscription data
  -- These fields are required by Web Push API for message encryption
  -- See: https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription
  endpoint TEXT NOT NULL,   -- Push service URL (unique per subscription)
  p256dh TEXT NOT NULL,     -- Public key for P-256 ECDH encryption (base64-encoded)
  auth TEXT NOT NULL,       -- Authentication secret for message authentication (base64-encoded)

  -- Audit timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraints
  -- One subscription per device per user (subscriptions are device-scoped)
  -- This prevents duplicate subscriptions when re-registering same device
  UNIQUE(user_id, device_id)
);

-- ============================================================================
-- Documentation Comments
-- ============================================================================

COMMENT ON TABLE push_subscriptions IS 'Web Push notification subscriptions scoped per device for multi-device support. Each browser/PWA instance gets its own push endpoint. Used for budget alerts (80%+ threshold) and transaction reminders (Phase C).';

COMMENT ON COLUMN push_subscriptions.device_id IS 'Links subscription to specific device from devices table. Push subscriptions are device-scoped - each browser instance has unique endpoint. ON DELETE CASCADE ensures cleanup when device is removed.';

COMMENT ON COLUMN push_subscriptions.endpoint IS 'Push service URL provided by browser Push API. Unique identifier for this subscription. Used to send push messages via Web Push Protocol.';

COMMENT ON COLUMN push_subscriptions.p256dh IS 'P-256 ECDH public key for message encryption (base64-encoded). Required by Web Push API for encrypting notification payloads. Generated by browser, never changes for subscription lifetime.';

COMMENT ON COLUMN push_subscriptions.auth IS 'Authentication secret for message authentication (base64-encoded). Required by Web Push API for HMAC verification. Generated by browser alongside p256dh key.';

-- ============================================================================
-- Indexes (2 strategic indexes for common query patterns)
-- ============================================================================

-- User's subscriptions lookup (for sending notifications to all user's devices)
CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);
COMMENT ON INDEX idx_push_subscriptions_user_id IS 'Supports fetching all push subscriptions for a user across their devices. Used when sending notifications to all user devices.';

-- Device's subscription lookup (for device management and unsubscribe)
CREATE INDEX idx_push_subscriptions_device_id ON push_subscriptions(device_id);
COMMENT ON INDEX idx_push_subscriptions_device_id IS 'Supports device-specific subscription queries. Used for unsubscribe operations and device management UI.';

-- ============================================================================
-- Trigger for updated_at
-- ============================================================================

CREATE TRIGGER update_push_subscriptions_updated_at
  BEFORE UPDATE ON push_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TRIGGER update_push_subscriptions_updated_at ON push_subscriptions IS
  'Automatically updates updated_at timestamp on row modification';

-- ============================================================================
-- Row Level Security (RLS)
-- ============================================================================

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can view their own subscriptions
CREATE POLICY "Users can view their own subscriptions"
  ON push_subscriptions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

COMMENT ON POLICY "Users can view their own subscriptions" ON push_subscriptions IS
  'Users can SELECT their own push subscriptions across all their devices';

-- Policy 2: Users can insert their own subscriptions
CREATE POLICY "Users can insert their own subscriptions"
  ON push_subscriptions FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

COMMENT ON POLICY "Users can insert their own subscriptions" ON push_subscriptions IS
  'Users can INSERT new push subscriptions when registering a device for notifications';

-- Policy 3: Users can update their own subscriptions
CREATE POLICY "Users can update their own subscriptions"
  ON push_subscriptions FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

COMMENT ON POLICY "Users can update their own subscriptions" ON push_subscriptions IS
  'Users can UPDATE their own push subscriptions (e.g., when endpoint changes)';

-- Policy 4: Users can delete their own subscriptions
CREATE POLICY "Users can delete their own subscriptions"
  ON push_subscriptions FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

COMMENT ON POLICY "Users can delete their own subscriptions" ON push_subscriptions IS
  'Users can DELETE their own push subscriptions when unsubscribing from notifications';

-- ============================================================================
-- Budget Threshold Check Function (RPC for Edge Functions)
-- ============================================================================

-- Function: check_budget_thresholds()
-- Purpose: Calculate budget spending vs targets and return budgets >= 80% threshold
-- Usage: Called by Supabase Edge Function for daily budget alert notifications
-- Returns: Budgets that have reached or exceeded 80% of their target amount
--
-- CRITICAL: This function MUST exclude transfers (transfer_group_id IS NULL)
--           to prevent double-counting in budget calculations.
--
-- Design:
-- 1. Join budgets with categories for display names
-- 2. LEFT JOIN transactions to calculate actual spending
-- 3. Use DATE_TRUNC for month matching with 'Asia/Manila' timezone
-- 4. Exclude transfers (WHERE transfer_group_id IS NULL)
-- 5. Sum only expense transactions (type = 'expense')
-- 6. Filter for current/future months only
-- 7. Calculate percentage: (spent_cents * 100 / amount_cents)
-- 8. Return budgets >= 80% threshold ordered by percentage DESC

CREATE OR REPLACE FUNCTION check_budget_thresholds()
RETURNS TABLE (
  id UUID,
  user_id UUID,
  category_id UUID,
  category_name TEXT,
  amount_cents BIGINT,
  spent_cents BIGINT,
  percentage INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  WITH budget_spending AS (
    SELECT
      b.id,
      b.household_id,  -- Added: needed for CROSS JOIN with profiles
      b.category_id,
      b.amount_cents,
      c.name AS category_name,
      -- Calculate actual spending for this budget's month and category
      -- CRITICAL: Exclude transfers to avoid double-counting
      COALESCE(SUM(
        CASE
          WHEN t.type = 'expense' AND t.transfer_group_id IS NULL
          THEN t.amount_cents
          ELSE 0
        END
      ), 0) AS spent_cents
    FROM budgets b
    INNER JOIN categories c ON b.category_id = c.id
    LEFT JOIN transactions t ON
      t.category_id = b.category_id
      -- Match transactions to budget month using Asia/Manila timezone
      -- DATE_TRUNC returns first day of month for both sides
      AND DATE_TRUNC('month', t.date AT TIME ZONE 'Asia/Manila') = DATE_TRUNC('month', b.month AT TIME ZONE 'Asia/Manila')
      -- CRITICAL: Exclude transfers from budget calculations
      -- Transfers are paired transactions (expense + income) that net to zero
      -- Including them would incorrectly inflate spending totals
      AND t.transfer_group_id IS NULL
    WHERE
      -- Only check current and future months (ignore historical budgets)
      b.month >= DATE_TRUNC('month', NOW() AT TIME ZONE 'Asia/Manila')
    GROUP BY b.id, b.household_id, b.category_id, b.amount_cents, c.name
  )
  SELECT
    bs.id,
    -- Get all users in the household (budgets are household-scoped per budgets table design)
    -- Each household member receives the budget alert (aligned with household financial management)
    p.id AS user_id,
    bs.category_id,
    bs.category_name,
    bs.amount_cents,
    bs.spent_cents,
    -- Calculate percentage of budget used
    -- Use integer division after scaling to avoid floating point
    CASE
      WHEN bs.amount_cents > 0
      THEN ((bs.spent_cents * 100) / bs.amount_cents)::INTEGER
      ELSE 0
    END AS percentage
  FROM budget_spending bs
  CROSS JOIN profiles p  -- Alert all household members
  WHERE
    p.household_id = bs.household_id  -- Match household
    AND bs.amount_cents > 0
    AND ((bs.spent_cents * 100) / bs.amount_cents) >= 80  -- 80% threshold
  ORDER BY percentage DESC;
END;
$$;

-- ============================================================================
-- Function Documentation
-- ============================================================================

COMMENT ON FUNCTION check_budget_thresholds() IS
  'Returns budgets that have reached 80%+ of their target amount. Used by Edge Functions for daily budget alert notifications. CRITICAL: Excludes transfers (transfer_group_id IS NULL) to prevent double-counting in budget calculations. Uses Asia/Manila timezone for month boundaries per profiles.timezone default.';

-- ============================================================================
-- Verification Queries
-- ============================================================================

DO $$
DECLARE
  table_exists BOOLEAN;
  function_exists BOOLEAN;
  column_count INT;
  index_count INT;
  trigger_count INT;
  policy_count INT;
BEGIN
  -- Check table exists
  SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_name = 'push_subscriptions'
  ) INTO table_exists;

  IF NOT table_exists THEN
    RAISE EXCEPTION 'push_subscriptions table was not created';
  END IF;

  -- Check columns
  SELECT COUNT(*) INTO column_count
  FROM information_schema.columns
  WHERE table_name = 'push_subscriptions';

  IF column_count < 7 THEN
    RAISE EXCEPTION 'push_subscriptions table has insufficient columns (found %)', column_count;
  END IF;

  -- Check indexes (should have 2 custom indexes + 1 primary key + 1 unique constraint)
  SELECT COUNT(*) INTO index_count
  FROM pg_indexes
  WHERE tablename = 'push_subscriptions';

  IF index_count < 2 THEN
    RAISE WARNING 'Expected at least 2 custom indexes, found %', index_count;
  END IF;

  -- Check triggers (should have 1: updated_at)
  SELECT COUNT(*) INTO trigger_count
  FROM information_schema.triggers
  WHERE event_object_table = 'push_subscriptions';

  IF trigger_count < 1 THEN
    RAISE WARNING 'Expected at least 1 trigger, found %', trigger_count;
  END IF;

  -- Check RLS policies (should have 4: SELECT, INSERT, UPDATE, DELETE)
  SELECT COUNT(*) INTO policy_count
  FROM pg_policies
  WHERE tablename = 'push_subscriptions';

  IF policy_count != 4 THEN
    RAISE WARNING 'Expected 4 RLS policies, found %', policy_count;
  END IF;

  -- Check function exists
  SELECT EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON p.pronamespace = n.oid
    WHERE n.nspname = 'public'
      AND p.proname = 'check_budget_thresholds'
  ) INTO function_exists;

  IF NOT function_exists THEN
    RAISE EXCEPTION 'check_budget_thresholds() function was not created';
  END IF;

  RAISE NOTICE 'push_subscriptions table created successfully with % columns, % indexes, % triggers, % policies',
    column_count, index_count, trigger_count, policy_count;

  RAISE NOTICE 'check_budget_thresholds() function created successfully';

END $$;

COMMIT;

-- ============================================================================
-- Rollback Instructions
-- ============================================================================
-- If this migration needs to be rolled back, create a new migration with:
--
-- BEGIN;
--
-- -- Drop function
-- DROP FUNCTION IF EXISTS check_budget_thresholds();
--
-- -- Drop RLS policies (reverse order)
-- DROP POLICY IF EXISTS "Users can delete their own subscriptions" ON push_subscriptions;
-- DROP POLICY IF EXISTS "Users can update their own subscriptions" ON push_subscriptions;
-- DROP POLICY IF EXISTS "Users can insert their own subscriptions" ON push_subscriptions;
-- DROP POLICY IF EXISTS "Users can view their own subscriptions" ON push_subscriptions;
--
-- -- Drop trigger
-- DROP TRIGGER IF EXISTS update_push_subscriptions_updated_at ON push_subscriptions;
--
-- -- Drop indexes (reverse order)
-- DROP INDEX IF EXISTS idx_push_subscriptions_device_id;
-- DROP INDEX IF EXISTS idx_push_subscriptions_user_id;
--
-- -- Drop table
-- DROP TABLE IF EXISTS push_subscriptions;
--
-- COMMIT;
--
-- WARNING: Rolling back will delete ALL push subscription records.
-- Only rollback if migration fails during initial application.
